import os
print("")
print("")
print("__file__ == \"{}\"".format(__file__))
print("")
print("type(__file__) == {}".format(type(__file__)))
print("")
print("os.path.dirname(__file__) == \"{}\"".format(os.path.dirname(__file__)))
print("")
print("type(os.path.dirname(__file__)) == {}".format(type(os.path.dirname(__file__))))
print("")
print("os.path.abspath(__file__) == \"{}\"".format(os.path.abspath(__file__)))
print("")
print("type(os.path.abspath(__file__)) == {}".format(type(os.path.abspath(__file__))))
print("")
print("")
print("")
os.system("pause")
